# -*- coding: utf-8 -*-
"""rag_document_assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilcPCxg2COH9G0M87RZFR70Dxk22h3q6
"""

!pip install pypdf sentence-transformers faiss-cpu

import os
print(os.listdir())

from pypdf import PdfReader

file_path = "(Toluwani Oyewusi) Fall 2026 Statement of Purpose_ Kennesaw State University.pdf"

reader = PdfReader(file_path)

documents = []
for page in reader.pages:
    text = page.extract_text()
    if text:
        documents.append(text)

print(f"Pages loaded: {len(documents)}")

# Simple splitter without LangChain
chunk_size = 1000  # characters per chunk
overlap = 200

chunks = []
for page in documents:
    start = 0
    while start < len(page):
        end = start + chunk_size
        chunk_text = page[start:end]
        chunks.append(chunk_text)
        start += chunk_size - overlap

print(f"Total chunks: {len(chunks)}")

from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-v2')

# Create embeddings for all chunks
embeddings = model.encode(chunks, convert_to_numpy=True)

print(f"Embeddings shape: {embeddings.shape}")

import faiss

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

print(f"Number of vectors in index: {index.ntotal}")

# query = "What is this statement of purpose about?"

# query_embedding = model.encode([query])

# k = 3  # number of results
# distances, indices = index.search(query_embedding, k)

# print(distances, indices)
# for i in indices[0]:
#     print("\n---\n")
#     print(chunks[i])

import os
from getpass import getpass

os.environ["OPENAI_API_KEY"] = getpass()

!pip install openai

from openai import OpenAI

client = OpenAI()

query = "What is this statement of purpose about?"

# Convert query → embedding
query_embedding = model.encode([query])

# Retrieve top chunks
k = 3
distances, indices = index.search(query_embedding, k)

retrieved_text = ""
for i in indices[0]:
    retrieved_text += chunks[i] + "\n\n"

# Send to LLM
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "Answer the question based only on the provided context."},
        {"role": "user", "content": f"Context:\n{retrieved_text}\n\nQuestion: {query}"}
    ],
    max_tokens=200
)

print(response.choices[0].message.content)